### ISSUE TITLE
Simple to Use Proofs and Program Verification

### ISSUE THREAD

**Issue by sirinath** [vrtbl/passerine#24]
Can simple to use proofs be added to the language in the spirit of [Formality](https://github.com/moonad/Formality), [ATS Programming Language](http://www.ats-lang.org/), [Why3/WhyML](http://why3.lri.fr/), [Whiley](http://whiley.org/), [SPARK](https://en.wikipedia.org/wiki/SPARK_(programming_language)) or [Dafny](https://github.com/dafny-lang/dafny).

**Comment by slightknack** [comment]
Potentially in the future, but this isn't the main use-case for Passerine, and the type system hasn't been fully implemented yet. I'm closing this issue for now; once we're reached the point where proofs may be possible, consider re-opening it :)
