### ISSUE TITLE
Github Sponsorship

### ISSUE THREAD

**Issue by Kethku** [vrtbl/passerine#54]
This project is really cool and I'd like to sponsor the development of it :)

**Comment by slightknack** [comment]
Thank you! I've been accepted into the GitHub sponsors program, I just haven't had the time to set it up yet. I'll be sending you an email asking for more information about the nature of this sponsorship soon :)

I also plan to make an announcement regarding a few major changes to the project (basically organizing some things so development moves at a quicker pace). It won't change who's working on everything, just how those things are worked on. More coming soon.

**Comment by Kethku** [comment]
Just a quick ping @slightknack any progress on getting github sponsors setup?

**Comment by slightknack** [comment]
I've run into an issue with stripe while setting up a github sponsors account, and I'm not sure how to proceed - I've sent you some more information over discord. The tl;dr is I might have to use a platform other than GitHub sponsors for the time being.

**Comment by slightknack** [comment]
@Kethku I've set up a [Patreon](https://www.patreon.com/slightknack) for now. I might migrate to GitHub sponsors once it becomes a possibility. Thank you!
