### ISSUE TITLE
Syntax example

### ISSUE THREAD

**Issue by TheodoreSnoozevelt** [vrtbl/passerine#8]
Am I stupid?

    linear = m b x -> b + m * x
    linear 2 3 5
    -- evaluates to 17

- `2` is matched against `m`, so `m = 2`,
- `3` against `b`, so `b = 3`,
- `5` against `x`, so `x = 5`,

If `b = 3`,  why is this `2 + 3 * 5` instead of `3 + 2 * 5`?

**Comment by slightknack** [comment]
Good catch! It was a different example earlier, but I changed it. Fixed it!
